AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Práctica intermodular serverless
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  # API Gateway explícito para CORS
  NotesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        AllowOrigin: "'*'"

  # Función Lambda para leer las notas de un usuario
  getNotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getNotes.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para leer las notas de la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable
      # Cambios añadidos
      Events:
        GetNotesApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi  
            Path: /notes
            Method: get

# Función Lambda para obtener una única nota de un usuario
  getNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para leer una nota específica de un usuario determinado
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable
      # Cambios añadidos
      Events:
        GetNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi  
            Path: /notes/{noteId}
            Method: get

  # Función Lambda para crear una nota para un usuario
  postNotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/postNotes.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para devolver una nota en la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable
      # Cambios añadidos
      Events:
        postNotesApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi  
            Path: /notes
            Method: post

  # Función Lambda para procesar las notas para un usuario
  processNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/processNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para procesar una nota en la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable
      # Cambios añadidos
      Events:
        processNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi  
            Path: /notes/{noteId}/process
            Method: post

  # Función Lambda para poner las notas para un usuario
  putNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para editar una nota en la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable
      # Cambios añadidos
      Events:
        putNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi  
            Path: /notes/{noteId}
            Method: put

  # Función Lambda para borrar una nota para un usuario
  deleteNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/deleteNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para borrar una nota en la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable
      # Cambios añadidos
      Events:
        deleteNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi  
            Path: /notes/{noteId}
            Method: delete

  # Tabla DynamoDB
  # Observa que no vamos a utilizar el recurso AWS::Serverless::SimpleTable, porque
  # solo deja definir clave de partición y no clave de ordenación
  # Por tanto, incluimos un recurso AWS::DynamoDB::Table de CloudFormation
  # Puedes comprobar por tanto que en plantillas SAM se pueden incluir también recursos
  # de CloudFormation
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId # Si lo deseas, puedes cambiar el nombre de las claves. Recuerda actualizar el código también
          AttributeType: S
        - AttributeName: noteId # Si lo deseas, puedes cambiar el nombre de las claves. Recuerda actualizar el código también
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

# Salidas para mostrar el nombre de las funciones que se han creado
Outputs:
  getNotesFunctionName:
    Value: !Ref getNotes
  getNoteFunctionName:
    Value: !Ref getNote
  postNotesFunctionName:
    Value: !Ref postNotes
  postNotesFunctionName:
    Value: !Ref processNote
  postNotesFunctionName:
    Value: !Ref putNote
  deleteNoteFunctionName:
    Value: !Ref deleteNote
# Añade también un Output para la dirección del API Gateway que genere (opcional, pero buena práctica).
  NotesApiUrl:
    Description: "URL de la API Gateway"
    Value: !Sub "https://${NotesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notes"